// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: examples/catalog/api/catalog.proto

package api

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCatalogGetItem = "/interview.catalog.v1.Catalog/GetItem"

type CatalogHTTPServer interface {
	GetItem(context.Context, *GetItemRequest) (*GetItemReply, error)
}

func RegisterCatalogHTTPServer(s *http.Server, srv CatalogHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/items/{id}", _Catalog_GetItem0_HTTP_Handler(srv))
}

func _Catalog_GetItem0_HTTP_Handler(srv CatalogHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetItemRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCatalogGetItem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetItem(ctx, req.(*GetItemRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetItemReply)
		return ctx.Result(200, reply)
	}
}

type CatalogHTTPClient interface {
	GetItem(ctx context.Context, req *GetItemRequest, opts ...http.CallOption) (rsp *GetItemReply, err error)
}

type CatalogHTTPClientImpl struct {
	cc *http.Client
}

func NewCatalogHTTPClient(client *http.Client) CatalogHTTPClient {
	return &CatalogHTTPClientImpl{client}
}

func (c *CatalogHTTPClientImpl) GetItem(ctx context.Context, in *GetItemRequest, opts ...http.CallOption) (*GetItemReply, error) {
	var out GetItemReply
	pattern := "/v1/items/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCatalogGetItem))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
